### ISSUE TITLE
Can't use 2 oblivion pills

### ISSUE THREAD

**Issue by Kiuden** [jrmycsm/dix-oblivionpill#1]
If you use a oblivion pill, it works.
If you use it again later without restarting, it doesn't work.

**Comment by Mr-Pleb** [comment]
Edit you client/main.lua to

`locksound = false
local pillused = false

RegisterNetEvent('dix-oblivionpill:piluleoubli')
AddEventHandler('dix-oblivionpill:piluleoubli', function()
    pillused = true
end)

Citizen.CreateThread(function()
    while true do
		print(pillused)
        Citizen.Wait(0)
        if pillused == true then

            StartScreenEffect("DeathFailOut", 0, 0)
            if not locksound then
                PlaySoundFrontend(-1, "Bed", "WastedSounds", 1)
                locksound = true
                pillused = true
            end
            ShakeGameplayCam("DEATH_FAIL_IN_EFFECT_SHAKE", 1.0)

            local scaleform = RequestScaleformMovie("MP_BIG_MESSAGE_FREEMODE")

            if HasScaleformMovieLoaded(scaleform) then
                Citizen.Wait(0)

                PushScaleformMovieFunction(scaleform, "SHOW_SHARD_WASTED_MP_MESSAGE")
                BeginTextComponent("STRING")
                AddTextComponentString(_U('fall_oubli'))
                EndTextComponent()
                PopScaleformMovieFunctionVoid()

                Citizen.Wait(100)
                PlaySoundFrontend(-1, "TextHit", "WastedSounds", 1)
                while pillused == true do
                    DrawScaleformMovieFullscreen(scaleform, 255, 255, 255, 255)
                    SetPedToRagdoll(GetPlayerPed(-1), 1000, 1000, 0, 0, 0, 0)
                    DisablePlayerFiring(PlayerId(), true)
                    Citizen.Wait(0)
                end

                StopScreenEffect("DeathFailOut")
                locksound = false

            end
        end
    end
end)

RegisterNetEvent('dix-oblivionpill:stoppill')
AddEventHandler('dix-oblivionpill:stoppill', function()
    stopPill()
end)

function stopPill()
    pillused = false
end
`

**Comment by IngPleb** [comment]
Edit your client/main.lua to this

https://pastebin.com/f8wKy8J0

**Comment by jrmy-dev** [comment]
Fixed thanks to Mr-Pleb!
